package com.savaava.mytvskeeper.main;

import com.savaava.mytvskeeper.exceptions.VideoAlreadyExistsException;
import com.savaava.mytvskeeper.models.*;
import com.savaava.mytvskeeper.services.TMDatabase;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

public class Test {
    private static final String[] MOVIES = {
            "Mrs. Doubtfire",
            "Will Hunting - Genio ribello",
            "L'attimo fuggente",
            "Jumanji",
            "Una notte al museo 1",
            "Una notte al museo 2",
            "Una notte al museo 3",
            "Hook",
            "One Hour Photo",
            "Licenza di matrimonio",
            "Pulp fiction",
            "Bastardi senza gloria",
            "Django Unchained",
            "Once Upon A Time in Hollywood",
            "The Hateful Eight",
            "Kill Bill vol.1",
            "Kill Bill vol.2",
            "Le iene",
            "Hannibal",
            "American Gangster",
            "Gucci",
            "Il Gladiatore",
            "The Last Duel",
            "Robin Hood",
            "Blade Runner 2048",
            "Blade Runner 2049",
            "Exodus - Dei e Re",
            "Alien",
            "Promotheus",
            "Alien Covenant",
            "Legend",
            "Napoleon",
            "Sopravvissuto - The Martian",
            "Her",
            "Essere John Malkovich",
            "Il ladro di orchidee",
            "Pride and Prejudice 2005",
            "Casino Royale",
            "Quantum of Solace",
            "Skyfall",
            "Spectre",
            "No Time to Die",
            "Robin Hood – L'origine della leggenda",
            "Sherlock Holmes",
            "Sherlock Holmes - Gioco di Ombre",
            "King Arthur",
            "The Man From UNCLE",
            "Snatch - Lo strappo",
            "Matrix",
            "Matrix 2",
            "Matrix Revolutions",
            "Matrix Resurrection",
            "Star Wars - La Minaccia Fanstasma",
            "Star Wars - L'attacco dei Cloni",
            "Star Wars - La vendetta dei Sith",
            "Star Wars",
            "Star Wars - L'impero colpisce ancora",
            "Star Wars - Il Ritorno dello Jedi",
            "Star Wars - Rogue One",
            "Star Wars - Il risveglio della forza",
            "Star Wars - Gli ultimi Jedi",
            "Star Wars - L'ascesa di Skywalker",
            "Star Wars - The Clone Wars 2008 ",
            "Indiana Jones and the Temple of Doom",
            "Indiana Jones - Raiders of the Lost Ark",
            "Indiana Jones and the Last Crusade",
            "Indiana Jones e il teschio di cristallo",
            "Cloud Atlas",
            "Pirati! Briganti da strapazzo",
            "Wallace & Gromit - La maledizione del coniglio mannaro",
            "Giù per il tubo",
            "Sin City",
            "Sin City - Una donna per cui uccidere",
            "Speed",
            "Troy",
            "Fury",
            "World War Z",
            "Bullet train",
            "Ocean's Eleven",
            "La Grande Scommessa",
            "The Nice Guys",
            "First man - Il primo uomo",
            "La La Land",
            "Come un tuono 2012",
            "Drive",
            "Le pagine della nostra Vita",
            "Gangster Squad",
            "The Equalizer",
            "The Equalizer 2",
            "I magnifici 7",
            "Southpaw - L'ultima sfida",
            "Flight",
            "Cani sciolti",
            "L'uomo con i pugni di ferro",
            "A Beautiful Mind",
            "Il Giorno Sbagliato",
            "Noah",
            "Un'ottima annata",
            "Master & Commander",
            "The Next Three Days",
            "The Water Diviner",
            "La Mummia",
            "Sicario",
            "Non è un paese per vecchi",
            "Dune",
            "Oldboy 2013",
            "Everest",
            "Pacific Rim",
            "Pacific Rim - La rivolta",
            "La Torre Nera",
            "Star Trek - Into Darkness",
            "Léon ",
            "Warrior",
            "Into the Wild - Nelle terre selvagge",
            "Il professore e il pazzo",
            "The Gunman",
            "I sogni segreti di Walter Mitty",
            "Salvate il soldato Ryan",
            "Ted",
            "Un milione di modi per morire nel West",
            "I Simpson - Il Film",
            "Povere creature!",
            "Benvenuti a Zombieland",
            "Birdman",
            "Irrational Man",
            "Vizio di forma",
            "Snowden",
            "Solo per vendetta 2011",
            "Kick Ass",
            "Kick Ass 2",
            "USS Indianapolis",
            "The Founder",
            "Robocop 2014",
            "Il caso Spotlight",
            "Need for Speed",
            "Fast & Furious 5",
            "Fast & Furious 6",
            "Fast & Furious 7",
            "Fast & Furious 8",
            "Hobbs & Shawn",
            "In Time",
            "Mad Max - Fury Roads",
            "Atomica Bionda",
            "Biancaneve e il cacciatore",
            "Il cacciatore e la regina di ghiaccio",
            "Hancock",
            "Kubo e la spada magica",
            "Coraline e la porta magica",
            "Sausage Party",
            "Collateral Beauty",
            "Grand Budapest Hotel",
            "Fantastic Mr. Fox",
            "Moonrise Kingdom - Una fuga d'amore",
            "The French Dispatch",
            "L'isola dei cani",
            "Il treno per il Darjeeling",
            "Castello Cavalcanti",
            "Past Lives",
            "Ex Machina",
            "X: A Sexy Horror Story",
            "The Lighthouse",
            "Midsommar - Il villaggio dei dannati",
            "The Lobster",
            "The Green Knight",
            "Locke",
            "Minari",
            "We Live in Time",
            "The Menu",
            "Finché morte non ci separi",
            "Knives Out",
            "Glass Onion - Knives Out",
            "Taken - La vendetta",
            "The Grey",
            "Scemo e più scemo 2",
            "Scontro tra titani",
            "La furia dei titani",
            "Le cronache di Narnia - Il leone, la strega e l'armadio",
            "Le cronache di Narnia - Il principe Caspian",
            "Le cronache di Narnia - Il viaggio del veliero",
            "Schindler's List - La lista di Schindler",
            "E.T. l'extra-terrestre",
            "Jurassic Park",
            "Ready Player One",
            "Le avventure di Tintin - Il segreto dell'Unicorno",
            "La guerra dei mondi",
            "Lincoln",
            "Prova a prendermi",
            "Jurassic World – Il regno distrutto",
            "The Accountant",
            "The Town",
            "Argo",
            "Forrest Gump",
            "Sully",
            "The Polar Express",
            "Riddick 2013",
            "The Last Witch Hunter 2015",
            "Dungeons & Dragons - L'onore dei ladri",
            "Jack Reacher: Punto di non ritorno",
            "Jack Reacher - La prova decisiva",
            "Top Gun",
            "Cuori Ribelli",
            "Giorni di tuono",
            "Mission Impossible",
            "Mission Impossible 3",
            "Mission Impossible - Protocollo Fantasma",
            "Mission: Impossible - Rogue Nation",
            "Mission: Impossible – Fallout",
            "Eyes Wide Shut",
            "Edge of Tomorrow",
            "L'ultimo samurai",
            "Oblivion",
            "Un'occasione da Dio",
            "L'era glaciale 1",
            "L'era glaciale 2",
            "L'era glaciale 3",
            "L'era glaciale 4",
            "Rio",
            "Ortone e il mondo dei Chi",
            "Robots",
            "Il libro della vita",
            "Snoopy & Friends - Il film dei Peanuts",
            "Arrival",
            "American Hustle - L'apparenza inganna",
            "Il Cigno Nero",
            "I tre moschettieri 2011",
            "Il Signore degli Anelli - La compagnia dell'anello",
            "Il Signore degli Anelli - Le due torri",
            "Il Signore degli Anelli - Il ritorno del Re",
            "The Hobbit - Un viaggio inaspettato",
            "The Hobbit - La desolazione di Smaug",
            "The Hobbit - La battaglia delle 5 armate",
            "Green Book",
            "District 9",
            "Revenant Redivio",
            "Bronson",
            "Capone",
            "Predator",
            "Harry Potter e la Pietra Filosofale",
            "Harry Potter e la camera dei segreti",
            "Harry Potter e il prigioniero di Azkaban",
            "Harry Potter e il prigioniero di Azkaban",
            "Harry Potter e il calice di fuoco",
            "Harry Potter e l’Ordine della Fenice",
            "Harry Potter e il principe mezzosangue",
            "Harry Potter e i Doni della Morte - Parte 1",
            "Harry Potter e i Doni della Morte - Parte 2",
            "Animali fantastici e dove trovarli",
            "Animali fantastici e dove trovarli 2",
            "Terminator Genysis",
            "Escape Plan - Fuga dall'inferno",
            "Creed - Nato per combattere",
            "Creed 2",
            "Il grande match",
            "I mercenari",
            "I mercenari 2",
            "I mercenari 3",
            "I mercenari 4",
            "Now You See Me",
            "Now You See Me 2",
            "Victor - La storia segreta del dott. Frankenstein ",
            "Jeanne du Barry - La favorita del re",
            "Rango",
            "Transcendence",
            "Alice nel Paese delle Meraviglie - Attraverso lo specchio",
            "Assassinio sull'Orient Express",
            "Assassinio sul Nilo",
            "Assassinio a Venezia",
            "Mortdecai",
            "Pet Semetary",
            "L'alba del pianeta delle scimmie",
            "Apes Revolution - Il pianeta delle scimmie",
            "Red",
            "Red 2",
            "I figli degli uomini",
            "Closer",
            "I segreti di Brokeback Mountain",
            "Donnie Darko",
            "Prisoners",
            "Southpaw",
            "The Day After Tomorrow",
            "Demolition - Amare e vivere",
            "Prince of Persia - Le sabbie del tempo",
            "Source Code",
            "Gone Girl",
            "Zodiac 2007",
            "Seven",
            "The Killer",
            "The social Network",
            "Monster House",
            "Il quinto elemento",
            "JFK - Un caso ancora aperto",
            "Looper",
            "G.I. Joe - La nascita dei Cobra",
            "G.I. Joe – La vendetta",
            "Tolkien",
            "L'uomo che vide l'infinito ",
            "Il sapore del successo",
            "Il lato positivo",
            "American Sniper",
            "Zoolander",
            "Zoolander 2",
            "Anchorman - La leggenda di Ron Burgundy",
            "Anchorman 2 - Fotti la notizia",
            "Il grande Gatsby 2013",
            "Passengers",
            "The Hunger Games ",
            "The Hunger Games: Catching Fire",
            "The Crow",
            "Il Re 2019",
            "Macbeth 2015",
            "Pleasantville",
            "Peter Pan 2003",
            "Jumanji  - Benvenuti nella giungla",
            "I fantastici viaggi di Gulliver",
            "Waterworld",
            "American Beauty",
            "Shining",
            "Doctor Sleep",
            "Qualcuno volò sul nido del cuculo",
            "The Departed - Il bene e il male",
            "Killers of the Flower Moon",
            "The Wolf of Wall Street",
            "Shutter Island",
            "La legge della notte",
            "Uncharted 2022",
            "Le Mans '66 - La grande sfida",
            "Vice – L'uomo nell'ombra",
            "The Pale Blue Eye - I delitti di West Point",
            "American Psycho",
            "Equilibrium",
            "Free Guy - Eroe per gioco",
            "Pokémon: Detective Pikachu",
            "Cambio vita",
            "R.I.P.D. - Poliziotti dall'aldilà",
            "Espiazione - Atonement",
            "IT 1990",
            "IT 2019",
            "IT 2",
            "Filth",
            "Van Gogh - Sulla soglia dell'eternità",
            "John Wick",
            "John Wick 2",
            "John Wick 3",
            "John Wick 4",
            "The Great Wall",
            "La ragazza di Stillwater",
            "Invictus - L'invincibile",
            "Monuments Men",
            "Baby Driver",
            "L.A. Confidential",
            "We Are Your Friends",
            "Assassin's Creed 2016",
            "Steve Jobs 2015",
            "Jobs",
            "Kingsman: Secret Service",
            "Kingsman - Il cerchio d'oro",
            "The King's Man - Le origini",
            "Super Mario Bros - il film",
            "Un'impresa da Dio",
            "Beautiful Boy",
            "Agente Smart - Casino totale",
            "Dragon Trainer",
            "Dragon Trainer 2",
            "Dragon Trainer 3",
            "Megamind",
            "Shrek",
            "Shrek 2",
            "Shrek 3",
            "Madagascar",
            "Shark Tale",
            "Mostri contro Alieni",
            "Bee Movie",
            "Spirit - Cavallo selvaggio",
            "Kung Fu Panda",
            "Kung Fu Panda 2",
            "Kung Fu Panda 3",
            "Il principe d'Egitto",
            "Il gatto con gli stivali - L'ultimo desiderio",
            "La gang del bosco",
            "Le 5 leggende",
            "Giù per il tubo",
            "I croods",
            "Turbo",
            "Troppo cattivi",
            "Tartarughe Ninja 2014",
            "Tartarughe Ninja - Fuori dall'ombra",
            "TMNT (2007)",
            "Arthur e il popolo dei Minimei",
            "Total Recall - Atto di forza",
            "The Mask",
            "Il Grintch",
            "A Christmas Carol",
            "Sonic",
            "Sonic 2",
            "Space Jam: New Legends",
            "Tutto può accadere",
            "Tutto può cambiare",
            "The Imitation Game",
            "1917",
            "Black Mass - L'ultimo gangster",
            "Edison — L'uomo che illuminò il mondo",
            "500 days of summer",
            "L'avvocato del diavolo",
            "Oppenheimer",
            "Batman Begins",
            "Il Cavaliere Oscuro",
            "Il Cavaliere Oscuro - Il ritorno",
            "Interstellar",
            "Inception",
            "The prestige",
            "Memento",
            "Dunkirk",
            "Tenet",
            "La migliore offerta",
            "Il discorso del re",
            "Storia di una ladra di libri",
            "Army of Dead",
            "300",
            "300 l'alba di un impero",
            "Johnny English - La rinascita",
            "Adeline - L'eterna giovinezza",
            "About time",
            "R.I.P.D. - Poliziotti dall'aldilà",
            "Il grande Lebowski",
            "Don Jon",
            "Snowden",
            "The walk",
            "50 e 50",
            "10 cose che odio di te",
            "La Fabbrica di Cioccolato",
            "Edward mani di forbice",
            "Alice nel Paese delle Meraviglie",
            "Beetlejuice - Spiritello porcello",
            "Miss Peregrine - La casa dei bambini speciali",
            "Dark Shadows",
            "Ed Wood",
            "Mars Attacks!",
            "Big Eyes",
            "Eragon",
            "Transformers (2007)",
            "Transformers: Revenge of the Fallen (2009)",
            "Transformers: Dark of the Moon (2011) ",
            "Transformers: Age of Extinction (2014)",
            "Transformers: The Last Knight (2017)",
            "Pain & Gain - Muscoli e denaro",
            "Armageddon - Giudizio finale",
            "Il Gigante di Ferro",
            "50 Sfumature di Grigio",
            "Cell",
            "Misery non deve Morire",
            "Avatar",
            "Avatar 2",
            "Terminator",
            "Terminator 2",
            "Titanic",
            "Alita – Angelo della battaglia",
            "Point Break - Punto di rottura",
            "Sanctum",
            "Il silenzio degli innocenti",
            "Sully",
            "Terminator 3",
            "Terminator Salvation",
            "La finestra sul cortile",
            "The Imitation Game",
            "Saving Mr. Banks",
            "Lost in Translation ",
            "Agente Smart - Casino totale",
            "The Legend of Zorro",
            "Elysium",
            "Carol",
            "Gravity",
            "Money Monster - L'altra faccia del denaro",
            "The American",
            "Fuck you prof",
            "Fuck you prof 2",
            "Alien 2",
            "A Monster Calls",
            "La bussola d'oro",
            "Tick Tick Boom!",
            "Hacksaw Ridge",
            "Red Lights 2012",
            "Il piccolo principe 2015",
            "No country for old man",
            "Rush",
            "127 Ore",
            "Balle Spaziali",
            "Robin Hood - Un uomo in calzamaglia",
            "L'aereo più pazzo del mondo",
            "Frankenstein Junior",
            "Bohemian Rhapsody",
            "Hardcore",
            "Io sono Babbo Natale",
            "L’ultima notte di Amore",
            "Chiedimi se sono felice",
            "Il cosmo sul comò",
            "Il ricco, il povero e il maggiordomo",
            "Sono tornato",
            "Lui è tornato",
            "Quo vado?",
            "Cado dalle nubi",
            "Sole a catinella",
            "Tolo Tolo",
            "Ricomincio da tre",
            "Benvenuti al Sud",
            "Benvenuti al Nord",
            "La vita è bella",
            "Terraferma",
            "Palombella rossa",
            "Loro",
            "È stata la mano di Dio",
            "Manchester By the Sea",
            "Detachment - Il distacco",
            "Shakespeare in love",
            "Snowpierce",
            "Parasite",
            "Dungeons and dragons - Onore ai ladri",
            "The Intouchables",
            "Valiant - Piccioni da combattimento",
            "Mr. & Mrs. Smith",
            "Adèle e l'enigma del faraone",
            "Storia di un matrimonio",
            "L'uomo che uccise Don Chisciotte",
            "Macchine mortali",
            "La storia infinita",
            "Annabelle",
            "The Conjuring - Il caso Enfield ",
            "M3gan",
            "The Gallows - L'esecuzione",
            "Five Nights at Freddy's",
            "La notte del giudizio",
            "La notte del giudizio 2",
            "Unfriended",
            "Unfirended - Dark Web",
            "Split",
            "Glass",
            "Scappa - Get Out",
            "Upgrade",
            "L'uomo invisibile",
            "Vivarium",
            "Necropolis - La città dei morti",
            "Krampus - Natale non è sempre Natale",
            "Ghost in the Shell 2017",
            "Warcraft: L'inizio",
            "Independence Day 2",
            "Alvin Superstar",
            "Alvin Superstar 2",
            "Alvin Superstar 3",
            "Gold – La grande truffa",
            "King Kong Skull Island",
            "La vera storia di Jack lo squartatore - From Hell",
            "Lo sciacallo",
            "Monty Python and the Holy Grail 1975",
            "Monty Python's Life of Brian ",
            "Monty Python's The Meaning of Life",
            "The Shawshank Redemption - Le ali della libertà",
            "Il mago di Oz (The Wizard of Oz) 1939",
            "Il grande e potente Oz",
            "Nel fantastico mondo di Oz (Return to Oz) 1985",
            "Blue Valentine",
            "The Fighter",
            "Twilight",
            "The Twilight Saga: New Moon",
            "The Twilight Saga: Eclipse",
            "The Twilight Saga: Breaking Dawn - Parte 1",
            "The Twilight Saga: Breaking Dawn - Parte 2",
            "Viaggio al centro della Terra",
            "Zathura - Un'avventura spaziale",
            "La mummia - La tomba dell'Imperatore Dragone",
            "Inkheart - La leggenda di cuore d'inchiostro",
            "Troppo cattivi",
            "Piovono polpette",
            "Piovono polpette 2",
            "Bug & Elliot",
            "Hotel Transilvania",
            "Hotel Transilvania 2",
            "Hotel Transilvania 3",
            "Hotel Transilvania 4",
            "Angry Birds ",
            "Angry Birds 2",
            "Spider-Man: Into the Spider-Verse",
            "Spider-Man: Across the Spider-Verse",
            "Nope",
            "Dracula Untold",
            "Nottingh Hill",
            "One Day",
            "Amore e altri rimedi",
            "Ricatto d'amore",
            "Demoni e dei",
            "Mystic river",
            "Codice d'onore",
            "Percy Jackson e gli dei dell'Olimpo - Il ladro di fulmini 2010",
            "Percy Jackson e gli dei dell'Olimpo - Il mare dei mostri",
            "Colpa delle stelle",
            "Old People",
            "Gods of Egypt",
            "Heat - La sfida",
            "The Father",
            "Come far perdere la testa al capo",
            "Candyman 2021",
            "Il buco",
            "Arancia meccanica",
            "Full Metal Jacket",
            "Death Note",
            "30 anni in un secondo",
            "Tutti tranne te",
            "Finchè morte non ci separi",
            "Ti presento i miei 2000",
            "Mi presenti i tuoi 2004",
            "Vi presento i nostri",
            "Il mostro dei mari",
            "Come farsi lasciare in 10 giorni",
            "Jerry Maguire",
            "Jumper - Senza confini",
            "Cose nostre - Malavita",
            "Ghost Town",
            "Crazy Stupid Love",
            "La persona peggiore del mondo",
            "Margin Call",
            "Suspiria",
            "Real Steel",
            "Astro Boy",
            "40 anni vergine",
            "Respect",
            "Collateral",
            "Heart of the Sea – Le origini di Moby Dick",
            "Civiltà perduta",
            "Nomadland",
            "Maria",
            "A complete unkown",
            "Dredd - La legge sono io",
            "A star is born",
            "L'incredibile Hulk 2008",
            "Blade",
            "Blade 2",
            "Blade 3",
            "X-Men: First Class",
            "X-Men: Days of Future Past",
            "X-Men Origins: Wolverine",
            "X-Men: Apocalypse",
            "X-Men: Dark Phoenix",
            "X-Men",
            "X2: X-Men United",
            "X-Men: The Last Stand",
            "The Wolverine",
            "Logan",
            "Deadpool",
            "Deadpool 2",
            "Deadpool & Wolverine",
            "Spider-Man",
            "Spider-Man 2",
            "Spider-Man 3",
            "Fantastic Four 2005",
            "Fantastic Four: Rise of the Silver Surfer",
            "The Fantastic Four 2",
            "Iron Man",
            "Iron Man 2",
            "Iron Man 3",
            "Thor",
            "Thor 2",
            "Thor: The Dark World",
            "Thor: Ragnarok",
            "Thor: Love and Thunder",
            "Captain America: The First Avenger",
            "Captain America: The Winter Soldier",
            "Captain America: Brave New World",
            "Guardians of the Galaxy",
            "Guardians of the Galaxy Vol. 2",
            "Guardians of the Galaxy Vol. 3",
            "Big Hero 6",
            "Avengers",
            "Avengers: Age of Ultron",
            "Ant-Man",
            "Ant-Man and the Wasp",
            "Ant-Man and the Wasp: Quantumania",
            "Fantastic Four (2015)",
            "The Amazing Spider-Man",
            "The Amazing Spider-Man 2",
            "Captain America: Civil War",
            "Doctor Strange",
            "Doctor Strange nel Multiverso della Follia",
            "Black Panther",
            "Black Panther: Wakanda Forever",
            "Avengers: Infinity War",
            "Ant-Man and the Wasp",
            "Venom",
            "Venom: Let There Be Carnage",
            "Captain Marvel",
            "Avengers: Endgame",
            "Black Widow",
            "Hulk vs. Wolverine",
            "Hulk vs. Thor",
            "Spider-Man: Homecoming",
            "Spider-Man: Far From Home",
            "V per Vendetta",
            "Batman 1989",
            "Batman - Il ritorno",
            "Batman - La maschera del fantasma",
            "Batman Forever",
            "Batman & Robin",
            "Superman Returns",
            "Red",
            "Red2",
            "Watchman",
            "L'uomo d'acciaio",
            "Batman vs Superman",
            "Justice League - Snyder's Cut",
            "The Suicide Squad 2016",
            "The Suicide Squad 2021",
            "LEGO Batman - Il film",
            "Wonder Woman",
            "Aquaman",
            "Shazam!",
            "Batman of the Future - Il ritorno del Joker",
            "Batman: Under the Red Hood",
            "Batman: The Dark Knight Returns, Part 1",
            "Batman: The Dark Knight Returns, Part 2",
            "Batman vs. Robin",
            "Batman: The Killing Joke",
            "Justice League Dark",
            "Superman: Red Son",
            "The Batman 2022",
            "Joker",
            "Pirati dei Caraibi - La maledizione della prima luna",
            "Pirati dei Caraibi - La maledizione del forziere fantasma",
            "Pirati dei Caraibi - Ai confini del mondo",
            "Pirati dei Caraibi - Oltre i confini del mare",
            "Pirati dei Caraibi - La vendetta di Salazar",
            "The Lone Ranger",
            "Biancaneve e i sette nani",
            "Pinocchio",
            "Fantasia",
            "Fantasia 2000",
            "Dumbo 1941",
            "Dumbo 2019",
            "Nightmere Before Christmas",
            "Pocahontas",
            "Il gobbo di Notre Dame",
            "Bambi",
            "Cenerentola",
            "Alice nel paese delle Meraviglie",
            "Peter Pan",
            "Ritorno all'Isola che non c'è",
            "La bella addormentata",
            "La spada nella roccia",
            "Il Libro della giungla",
            "Gli aristogatti",
            "Robin Hood",
            "Tron 1982",
            "Tron: Legacy",
            "Good Morning, Vietnam",
            "La sirenetta",
            "La Bella e la Bestia",
            "Aladdin",
            "Il re leone",
            "La carica dei 101",
            "Mulan",
            "Tarzan",
            "Dinosauri 2000",
            "Le follie dell'imperatore",
            "Atlantide: L'impero perduto ",
            "Red & Toby",
            "Il pianeta del tesoro",
            "Koda Fratello Orso",
            "Valiant",
            "G-Force",
            "Pan – Viaggio sull'isola che non c'è",
            "Oceania",
            "Raperonzolo",
            "Frozen",
            "Frozen 2",
            "Zootopia",
            "Il BFG",
            "Crudelia",
            "Tomorrowland",
            "La famiglia Robinson",
            "Bolt",
            "Ralph Spaccattutto",
            "Ralph Spacca Internet",
            "Come d'incanto",
            "Maleficent",
            "Chicken Little",
            "Gli Incredibili",
            "Gli Incredibili 2",
            "Toy Story",
            "Toy Story 2",
            "Toy Story 3",
            "Toy Story 4",
            "A Bug's Life",
            "Monster Inc.",
            "Monster University",
            "Alla ricerca di Nemo",
            "Alla ricerca di Dory",
            "Ratatouille",
            "Wall-e",
            "Up",
            "Ribelle: The Brave",
            "Inide Out",
            "Il viaggio di Arlo",
            "Coco",
            "Soul ",
            "Luca",
            "Red",
            "Onward - Oltre la magia",
            "Lightyear - La vera storia di Buzz",
            "Elemental",
            "Cars",
            "Cars 2",
            "Cars 3",
            "Planes",
            "Ponyo",
            "Il castello Errante di Howl",
            "Nausicaa nella valle del Vento",
            "Principessa Mononoke",
            "I sospiri del mio cuore",
            "Arietty il mondo segreto",
            "La città incantata",
            "Laputa - Il castello nel cielo",
            "Il mio vicino Totoro",
            "Kiki consegne a domicilio",
            "Earwig la strega",
            "Pom Poko",
            "I miei vicini Yamada",
            "Porco Rosso",
            "La collina dei papaveri",
            "I racconti di Terramare",
            "Si alza il vento",
            "Il ragazzo e l'airone",
            "La tomba delle lucciole",
            "Quando c'era Marnie",
            "The Kingdom of Dreams and Madness",
            "La ricompensa del gatto",
            "Myazaki e l'airone",
            "La storia della principessa splendente",
            "Lupin III - Il castello di Cagliostro",
            "Paprika",
            "Tokyo Godfather",
            "Pefect Blue",
            "Millenium Actress",
            "Akira",
            "Ghost in the Shell 1995",
            "Vampire Hunter D 1985",
            "Lupin III - Il tesoro di Anastasia"
    };
    private static final String[] TVS = {
            "Love Death and Robots",
            "Black Mirror",
            "The Watcher",
            "La casa di Carta",
            "Squid Game",
            "After Life",
            "Castelvania",
            "Castlevania: Nocturne",
            "Arcane",
            "Stranger Things",
            "The Witcher",
            "La regina degli scacchi",
            "Mr Robot",
            "Gangs of London",
            "Gomorra",
            "The Last of Us",
            "Euphoria",
            "Games of Thrones",
            "The Penguin",
            "The Walking Dead",
            "Breaking Bad",
            "Dietro i suoi occhi",
            "Outlander",
            "I Griffin",
            "Futurama",
            "I Simpson",
            "Hunters",
            "Lord of The Rings: Gli anelli del potere",
            "Modern Family",
            "How I Met Your Mother",
            "Boris",
            "Taboo",
            "Peaky Blinders",
            "Bodyguard 2018",
            "The Office UK",
            "The Thick of It",
            "Pam & Tommy",
            "The Office USA",
            "The Bear",
            "Shogun",
            "The Patient",
            "Shameless",
            "The Whispers",
            "Only Murders in the Building",
            "Attack on Titans",
            "Memories",
            "Death Note",
            "Paranoia Agent",
            "Cowboy Bebop",
            "Star Wars The Clone Wars",
            "Star Wars Tales of the Jedi",
            "Star Wars Tales of the Empire",
            "Star Wars The Bad Batch",
            "The Mandalorian",
            "Kenobi",
            "Loki",
            "The Punisher",
            "Wanda Vision",
            "The Falcon and the Winter Soldier",
            "Moon Knight",
            "She-Hulk: Attorney at Law",
            "Secret Invasion",
            "Echo",
            "I am Groot",
            "Baymax!",
            "Legends",
            "Daredevil",
            "Mrs. Marvel",
            "Agatha All Along",
            "Short Circuit",
            "Sandman",
            "Arrow",
            "Swamp Thing"
    };

    private static void addVideosMarco(int index, String[] videos) throws Exception {
        VideoKeeper vk = VideoKeeper.getInstance();
        TMDatabase tmdb = new TMDatabase();

        int cont = 0;
        int contAdded = 0;
        Collection<String> videosNotFounded = new ArrayList<>();
        for(String videoName : videos){

            List<Video> videosFounded;
            if(index == 1)
                videosFounded = new ArrayList<>(tmdb.getMoviesByName(videoName));
            else
                videosFounded = new ArrayList<>(tmdb.getTVSeriesByName(videoName));

            cont++;
            if(videosFounded.isEmpty()){
                System.err.println("("+cont+") no tvs founded -> "+videoName);
                videosNotFounded.add(videoName);
                continue;
            }

            String videoIdToAdd = videosFounded.getFirst().getId();

            Movie movieToAdd;
            TVSerie tvToAdd;
            try {
                if (index == 1) {
                    movieToAdd = tmdb.getMovieById(videoIdToAdd);
                    vk.addMovie(movieToAdd);
                    System.out.println("(" + cont + ") " + videoName + " -> " + movieToAdd.getTitle() + " | Release Date=" + movieToAdd.getReleaseDate());
                } else {
                    tvToAdd = tmdb.getTVSerieById(videoIdToAdd);
                    vk.addTVSerie(tvToAdd);
                    System.out.println("(" + cont + ") " + videoName + " -> " + tvToAdd.getTitle() + " | Release Date=" + tvToAdd.getReleaseDate());
                }
                contAdded++;
            }catch(VideoAlreadyExistsException ex){
                System.err.println(videoName+" already exists");
                videosNotFounded.add(videoName);
            }

            if(cont%25 == 0){
                System.out.println("Riposo di 10 secondi...");
                Thread.sleep(10*1000);
            }
        }
        System.out.println("\nvideo added: "+contAdded+"\nMarco's video: "+cont+"\nvideo not added: "+(cont-contAdded)+"\n");
        videosNotFounded.forEach(vi -> System.out.println(vi));
    }

    public static void main(String[] args) throws Exception {
//        VideoKeeper vk = VideoKeeper.getInstance();
//        TMDatabase tmdb = new TMDatabase();

        addVideosMarco(1,MOVIES);
//        addVideosMarco(2,TVS);
    }
}
